NUMPY=Numerical python

In [23]:
a = np.arange(10)**3

In [24]:
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [26]:
a[0:6:2]

array([ 0,  8, 64], dtype=int32)

In [40]:
c=print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [29]:
a[:8:2] = 1000

In [30]:
a

array([1000,    1, 1000,   27, 1000,  125, 1000,  343,  512,  729],
      dtype=int32)

In [31]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
9.999999999999998
6.999999999999999
7.999999999999999
8.999999999999998


In [20]:
c=np.arange(10000).reshape(100, 100)

In [21]:
print(c)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [22]:
c.shape

(100, 100)

In [8]:
import numpy as np

In [16]:
x = np.array([[7, 3], [2, 4]])
x


array([[7, 3],
       [2, 4]])

In [9]:

ind = np.argsort(x, axis=1)  # sorts along last axis (across)
ind

array([[1, 0],
       [0, 1]], dtype=int64)

In [32]:
x = np.array([[3, 6], [2, 4]])
x

array([[3, 6],
       [2, 4]])

In [49]:
ind = np.argsort(b,axis=0)  # sorts along first axis (down)
ind

array([[0, 0],
       [1, 1]], dtype=int64)

In [43]:

ind = np.argsort(b, axis=0)  # sorts along last axis (across)
ind

array([[0, 0],
       [1, 1]], dtype=int64)

In [18]:
np.take_along_axis(x, ind, axis=1)

array([[3, 7],
       [2, 4]])

In [45]:
b = np.array([[2, 1], [ 7, 4]])


In [50]:
np.take_along_axis(b, ind, axis=0)

array([[2, 1],
       [7, 4]])

In [23]:
#first ella numbers ahh yum onnakki athukku aprom athoda place value find pannuthu
#1=(0,1),2=(0,0),7=(1,0),4=(1,1)
#ithukku aprom first vara ellarthayum split pannuthu, then second varatha ellam split pannuthu
ind = np.unravel_index(np.argsort(b, axis=None), b.shape)
ind

(array([0, 0, 1, 1], dtype=int64), array([1, 0, 1, 0], dtype=int64))

In [25]:
b[ind]

array([1, 2, 4, 7])

In [33]:
b= np.array([(1, 4), (5, 3)], dtype=[('x', '<i4'), ('y', '<i4')])

In [34]:
np.argsort(b, order=('x','y'))

array([0, 1], dtype=int64)

In [36]:
c= np.array([(7, 4), (5, 7)], dtype=[('x', '<i4'), ('y', '<i4')])

In [39]:
# x ahh oda indices ahh compare pannuna 7>5 appo [1,0]
np.argsort(c, order=('x','y'))

array([1, 0], dtype=int64)

In [55]:
c= np.array([(7, 3), (5, 7)], dtype=[('x', '<i4'), ('y', '<i4')])

In [56]:
np.argsort(c, order=('y','x'))

array([0, 1], dtype=int64)

In [40]:
#y ahh oda indices ahh compare pannuna (4,7) 4<7 so, we get [0,1]
np.argsort(c, order=('y','x'))

array([0, 1], dtype=int64)

In [41]:
a = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S1'), ('y', int)])
a.sort(order='y')
a

array([(b'c', 1), (b'a', 2)], dtype=[('x', 'S1'), ('y', '<i4')])

In [46]:
a = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S1'), ('y', int)])
a.sort(order='y')
a

array([(b'c', 1), (b'a', 2)], dtype=[('x', 'S1'), ('y', '<i4')])

In [65]:
a = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S2'), ('y', int)])
a.sort(order='y')
a

array([(b'c', 1), (b'a', 2)], dtype=[('x', 'S2'), ('y', '<i4')])

In [68]:
a = np.array([('a', 2), ('c', 1)], dtype=[('c', 'S1'), ('r', int)])
a.sort(order='c')
a

array([(b'a', 2), (b'c', 1)], dtype=[('c', 'S1'), ('r', '<i4')])

In [58]:
a = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S1'), ('y', int)])
a.sort(order='y')
a

array([(b'c', 1), (b'a', 2)], dtype=[('x', 'S1'), ('y', '<i4')])

In [51]:
import numpy as np

x = np.array([1, 5, 1, 4, 3])
y = np.array([9, 4, 9, 2, 1])

sorted_indices = np.lexsort((y, x))
print(sorted_indices)


[0 2 4 3 1]


In [53]:
#lexsort vanthu sort panna use aguthu keys ahh vechu inga rendu keys irukku ithula primary key y,secondary key vanthu x
# y ahh poruthu ithu sort pannum
import numpy as np

x = np.array([1, 5, 1, 4, 3])
y = np.array([9, 4, 9, 2, 1])

sorted_indices = np.lexsort((x, y))
print(sorted_indices)


[4 3 1 0 2]


In [54]:
import numpy as np

x = np.array([17, 5, 1, 4, 3])
y = np.array([9, 4, 9, 2, 1])

sorted_indices = np.lexsort((y, x))
print(sorted_indices)


[2 4 3 1 0]


In [69]:
import numpy as np
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [71]:
[surnames[i] + ", " + first_names[i] for i in ind]

['Galilei, Galileo', 'Hertz, Gustav', 'Hertz, Heinrich']

In [86]:
a = [1, 5, 1, 4, 3, 4, 4]  # First sequence
b = [9, 4, 0, 4, 0, 2, 1]  # Second sequence

In [90]:
np.argsort((b, a),axis=0)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [ ]:
np.argsort((b, a))

In [87]:
np.lexsort((a,b))

array([2, 4, 6, 5, 3, 1, 0], dtype=int64)

In [60]:
#ithula first b sort pannuthu athukku aprom a vaa poruthu sort pannuthu
np.argsort((b, a), kind='stable')

array([[2, 4, 6, 5, 1, 3, 0],
       [0, 2, 4, 3, 5, 6, 1]], dtype=int64)

In [61]:
np.argsort((a, b), kind='stable')

array([[0, 2, 4, 3, 5, 6, 1],
       [2, 4, 6, 5, 1, 3, 0]], dtype=int64)

In [74]:
#a, b um compare pannum athula sort panni indices ahh order pannum
#(1,0)=2, (1,9)=0, (3,0)=4
a = [1, 5, 1, 4, 3, 4, 4]  # First sequence
b = [9, 4, 0, 4, 0, 2, 1]
c= np.array([(ai, bi) for ai, bi in zip(a, b)], dtype = np.dtype([('x', int), ('y', int)]))
np.argsort(x)  # or np.argsort(x, order=('x', 'y'))

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [71]:
a = [1, 5, 1, 4, 3, 4, 4]  # First sequence
b = [9, 4, 0, 4, 0, 2, 1] 
[(a[i], b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

In [80]:
a = [1, 5, 1, 4, 3, 4, 4]  # First sequence
b = [9, 4, 0, 4, 0, 2, 1]
arr = np.asarray([b, a])

In [81]:

ind2 = np.lexsort(arr)
np.testing.assert_equal(ind2, ind)

In [82]:
np.testing.assert_equal(np.lexsort(arr, axis=0),np.lexsort(arr, axis=-1))

In [79]:
for i in range(3):
    print(np.lexsort((x[i], y[i])))

[2 3 0 1]
[2 0 3 1]
[1 0 3 2]


In [78]:
#[1,2,3,4]
#[2,2,1,1] rendu row  eduthu athula sort pannirukku (1,2)=0,(2,2)=1,(3,1)=2,(4,1)3
#y thaa primary key x thaan secondary key 2,3,0,1
#ithe mathiri thaan ellam
x = [[1, 2, 3, 4],
     [4, 3, 2, 1],
     [2, 1, 4, 3]]
y = [[2, 2, 1, 1],
     [1, 2, 1, 2],
     [1, 1, 2, 1]]
np.lexsort((x, y), axis=1)

array([[2, 3, 0, 1],
       [2, 0, 3, 1],
       [1, 0, 3, 2]], dtype=int64)

In [89]:
#primary key=x, secondary key = y
x = [[1, 2, 3, 4],
     [4, 3, 2, 1],
     [2, 1, 4, 3]]
y = [[2, 2, 1, 1],
     [1, 2, 1, 2],
     [1, 1, 2, 1]]
np.lexsort((y, x), axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

In [91]:
data = np.array([1, 2, 5])
ones = np.ones(3, dtype=float)
data + ones

array([2., 3., 6.])

In [92]:
data - ones


array([0., 1., 4.])

In [93]:
data * data


array([ 1,  4, 25])

In [95]:
data / ones

array([1., 2., 5.])

In [96]:
b = np.array([[1, 1], [2, 2]])

In [97]:
np.sum(b)

6

In [98]:
np.sum(b,axis=0)

array([3, 3])

In [99]:
np.sum(b,axis=1)

array([2, 4])

In [101]:
b.sum()

6

In [102]:
b.sum(axis=0)

array([3, 3])

In [105]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [107]:
print(data.max())
print(data.min())
print(data.sum())

2.0
1.0
3.0


In [108]:
data=np.array([1,2,3,4,5,6])

In [115]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [114]:
data.reshape([3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [122]:
data[0:3,0]
#0 la irunthu second row vara ellam venum but 0 index ahh irukkanum so, 1, 3, and 5 is the answer



array([1, 3, 5])

In [126]:
data.max(axis=0)

array([5, 6])

In [127]:
data.max(axis=1)

array([2, 4, 6])

In [133]:
item=np.array([[1,4],[2,3]])

In [130]:
item.max()

5

In [131]:
item.max(axis=0)

array([5, 4])

In [134]:
item.max(axis=1)

array([4, 3])

In [135]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [108]:
c=np.ones([6,3,3])

In [109]:
print(c)


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [110]:
c.ndim

3

In [140]:
np.zeros([4,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [141]:
a=np.random.default_rng()
a.random(4)

array([0.94781682, 0.42353223, 0.125421  , 0.15252634])

In [142]:
a.random(4)

array([0.53611468, 0.43783828, 0.95593945, 0.28682713])

In [143]:
a.random([4,3,2])

array([[[0.51103489, 0.74627105],
        [0.28720859, 0.12417174],
        [0.20651135, 0.51224896]],

       [[0.80360457, 0.28951713],
        [0.00415434, 0.00681257],
        [0.68331216, 0.93135677]],

       [[0.16346989, 0.24099801],
        [0.35874093, 0.14593544],
        [0.83148039, 0.42476737]],

       [[0.40296583, 0.50828364],
        [0.95746516, 0.66428272],
        [0.28957998, 0.09864856]]])

In [145]:
a.random(3)

array([0.24778497, 0.34894189, 0.2203729 ])

In [146]:
np.ones(3)

array([1., 1., 1.])

In [147]:
np.zeros(4)

array([0., 0., 0., 0.])

In [148]:
np.random.random(3)

array([0.08547827, 0.02068884, 0.68856186])

In [152]:
np.random.random((3, 2)) 


array([[0.54756916, 0.06207126],
       [0.83099744, 0.62777837],
       [0.09782369, 0.30638621]])

In [153]:
x = np.array([[4, 9, 2, 10],
              [6, 9, 7, 12]])

ptp=Peak-to-Peak.

Find the range. 

range= highest number-small number

In [156]:
#range kandu pidikuranga rows kulla
#range=big number-small number: 10-2=8, 12-6=6
np.ptp(x, axis=1)

array([8, 6])

In [157]:
np.ptp(x, axis=0)

array([2, 0, 5, 2])

In [161]:
y = np.array([[1, 127],
              [0, 127],
              [-1, 127],
              [-2, 127]], dtype=np.int8)
np.ptp(y, axis=1).view(np.uint8)


array([126, 127, 128, 129], dtype=uint8)

In [162]:
y = np.array([[1, 127],
              [0, 127],
              [-1, 127],
              [-2, 127]], dtype=np.int8)
np.ptp(y, axis=1)

array([ 126,  127, -128, -127], dtype=int8)

In [163]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [167]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.var(a)

1.25

In [168]:
a = np.zeros((2, 512*512), dtype=np.float32)
a[0, :] = 1.0
a[1, :] = 0.1
np.mean(a)

0.54999924

In [169]:
b = np.array([1, 3], dtype="timedelta64[D]")
np.mean(b)

numpy.timedelta64(2,'D')

In [170]:
a = np. array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
np.mean(a)


12.0

In [173]:
a = np. array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
np.mean(a, where=[[True], [False], [False]])
# nee vanthu first row kku mattum mean kandu pudinu solluthu
#5+9+13=27/3=9

9.0

Percentile

In [180]:
import numpy as np
a = np.array([[10, 7, 4], [3, 2, 1]])
a
#np.percentile(a, 50)
np.percentile(a, 50, axis=0)
#np.percentile(a, 50, axis=1)
#np.percentile(a, 50, axis=1, keepdims=True)

array([6.5, 4.5, 2.5])

In [178]:
#first naalu numbers ahh orderwise ahh eluthi 3,4,5,6 ithukku median find pannu that's all
c=np.array([[4,3],[5,6]])

In [177]:
np.percentile(c,50)

4.5

In [179]:
np.percentile(c,75)

5.25

In [181]:
#up and down
a = np.array([[10, 7, 4], [3, 2, 1]])
a
np.percentile(a, 50, axis=0)

array([6.5, 4.5, 2.5])

In [183]:
#row kkulla
a = np.array([[10, 7, 4], [3, 2, 1]])
np.percentile(a, 50, axis=1)



array([7., 2.])

In [185]:
a = np.array([[10, 7, 4], [3, 2, 1]])
np.percentile(a, 50, axis=1,keepdims=True)

array([[7.],
       [2.]])

In [186]:
m = np.percentile(a, 50, axis=0)
out = np.zeros_like(m)
np.percentile(a, 50, axis=0, out=out)


array([6.5, 4.5, 2.5])

In [192]:
b = a.copy()
np.percentile(b, 50, axis=1,overwrite_input=True)


array([7., 2.])

In [81]:
import numpy as np
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4],[5,6,7,8]])

In [82]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)


In [83]:
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [84]:
print(indices)


[0 1 2]


In [85]:
#evlo accupy pannirukkunu therinikkalam
print(occurrence_count)

[2 2 1]


Reversing 

Values ellam reverse la eluthalam

use flip()

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
reverse=np.flip(arr)

In [17]:
print("reverse=", reverse)

reverse= [8 7 6 5 4 3 2 1]


In [18]:
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4],[5,6,7,8]])

In [19]:
rev=np.flip(d)

In [20]:
print("rev:",rev)

rev: [[ 8  7  6  5]
 [ 4  3  2  1]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [22]:
rev=np.flip(d, axis=1)
print('rev:',rev)

rev: [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [ 4  3  2  1]
 [ 8  7  6  5]]


In [23]:
rev=np.flip(d, axis=0)
print('rev:',rev)

rev: [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [24]:
np.power(100, 9, dtype=np.int64)


1000000000000000000

In [25]:
np.power(100, 9, dtype=np.int32)

-1486618624

In [30]:

np.power(2,44,dtype=np.int64)

17592186044416

In [31]:
np.power(2,44,dtype=np.int32)

0

In [98]:
b=np.empty([1,3], dtype=np.int32)

In [99]:
print(b)

[[-614791104        635 -581534400]]


In [100]:
b.fill(3)

In [101]:
print(b)

[[3 3 3]]


In [102]:
b=np.empty([1,3], dtype=np.int64)
print(b)

[[       2731017079552                    0 -9223372036854644734]]


New array vanthu irukkura array la irunthe create panna porom

In [111]:
a=np.arange(5)

In [112]:
print(a)

[0 1 2 3 4]


In [116]:
b=a[np.newaxis,:]

In [117]:
print(b)

[[0 1 2 3 4]]


In [118]:
b=a[:,np.newaxis]

In [119]:
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [120]:
c=np.expand_dims(a,axis=0)

In [121]:
print(c)

[[0 1 2 3 4]]


In [122]:
c=np.expand_dims(a,axis=1)
print(c)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [123]:
m=np.arange(20)
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [126]:
np.hsplit(m,4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [140]:
m=np.arange(20)


In [147]:
c=m.reshape([5,2,2])

In [148]:
print(c)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [151]:
np.vsplit(c,5)

[array([[[0, 1],
         [2, 3]]]),
 array([[[4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11]]]),
 array([[[12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19]]])]